apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: rs8cssgof-go 
  janus-idp.io/tekton: rs8cssgof-go
  backstage.io/kubernetes-id: rs8cssgof-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: rs8cssgof-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml