apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rs8cssgof-go
  namespace: tssc-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"] 
spec:
  project: default
  source:
    path: ./app-of-apps
    repoURL: https://github.com/rhtap-rhdh-qe/rs8cssgof-go-gitops.git
    targetRevision: main
  destination:
    namespace: tssc-gitops
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels: 
        argocd.argoproj.io/managed-by: tssc-gitops
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
